### ISSUE TITLE
about the dummy gateway

### ISSUE THREAD

**Issue by depay** [projectcalico/libnetwork-plugin#66]
I’ve upgrade from 0.8.0 to 0.9.0, and my containers became unconnected...Finally i found that the default gateway in my container was `169.254.1.1`, which is changed is #51 . i am still not clear about that after reading the whole PR. Could anyone make some explanation for that? And how could i fix the whole cluster, besides rolling back to v0.8.0?

**Comment by depay** [comment]
could anybody help ? @robbrockbank @djosborne

**Comment by djosborne** [comment]
There's not a great paper trail on these changes, I don't think 51 is the actual cause of the issue, just a reaction to another change upstream. Let me explain -

Originally, Calico explicitly set the Gateway on the container's interface to be the `$IP` on it's Host (i.e. eth0 on the host.). @tomdee realized this was unnecessary. We can simply rely on the container sending its traffic to the default route since, on the host side, we're proxying all traffic from the container to the host anyways. Furthermore, we could set the gateway address to any value we wanted (so we chose the dummy address `169.254.1.1`) as long as the host accepted all traffic coming from the container. [#101 was created in libcalico](https://github.com/projectcalico/libcalico/pull/101), and [#897 was created in calico-containers](https://github.com/projectcalico/calico-containers/pull/897/files). 

These changes broke libnetwork-plugin, So #51 was merged to stop trying to read the assigned gateway address, and instead just use / expect the known dummy address.

This is my understanding of the problem, but since @tomdee was the main one to implement these changes, maybe he can correct me or elaborate. Time spent on a good explanation here will also help complete [#66 - document use of link-local address as default gateway](https://github.com/projectcalico/calico/issues/66).

**Comment by depay** [comment]
thanks for the explanation @djosborne ! but what's the meaning for `on the host side, we're proxying all traffic from the container to the host anyways`? 

On my host, there's only 
```
# tcpdump -i cali8206253672f -n
tcpdump: WARNING: cali8206253672f: no IPv4 address assigned
tcpdump: verbose output suppressed, use -v or -vv for full protocol decode
listening on cali8206253672f, link-type EN10MB (Ethernet), capture size 65535 bytes
15:10:38.691942 ARP, Request who-has 169.254.1.1 tell 10.16.97.54, length 28
15:10:39.692471 ARP, Request who-has 169.254.1.1 tell 10.16.97.54, length 28
15:10:40.694466 ARP, Request who-has 169.254.1.1 tell 10.16.97.54, length 28
...
```
while the container ip is `10.16.97.54`.

Is there any other configuration or components needed, besides calico-node & calico-libnetwork-plugin ?

**Comment by djosborne** [comment]
I should have said "forwarding", not "proxying".

After that ARP comes in, the Host does a "Proxy ARP Response" telling the container it has `169.254.1.1` (even though it doesn't). The container should then forward it's traffic to the host.

There are no other configurations or components needed besides those two. 

If you're not seeing an ARP response sent back out that interface, proxy arp must not be functioning correctly. Probably it's going out `eth0` to the host's nexthop? Worth checking if your kernel supports [proxy_arp](http://www.sjdjweis.com/linux/proxyarp/)

**Comment by djosborne** [comment]
proxy-arp is [enabled by felix when it configures the caliXX interface](https://github.com/projectcalico/felix/blob/9784de9b32b04d21ce74762abfea5800ace0ad52/calico/felix/devices.py#L242).

**Comment by depay** [comment]
i'm using CentOS 7.2 with kernel `3.10.0-327` supporting proxy_arp.

```
[   10.811390] ip_tables: (C) 2000-2006 Netfilter Core Team
[   12.333546] nf_conntrack version 0.5.0 (65536 buckets, 262144 max)
```

```
# cat /proc/sys/net/ipv4/conf/calif5a3af1281e/proxy_arp
1
# cat /proc/sys/net/ipv4/conf/all/proxy_arp
0
# cat /proc/sys/net/ipv4/conf/eth0/proxy_arp
0
```

Is the default route such as `default dev eth0  scope link` or route for `169.254.0.0/16` necessary for this function ? Containers connected when i added it..

**Comment by matthewdupre** [comment]
Yes, the host needs to think it can route to 169.254.1.1 over an interface other than cali* (a default route is fine).

**Comment by matthewdupre** [comment]
You might want to add a dummy interface with 169.254.1.1 on it, for example.

**Comment by depay** [comment]
thanks @matthewdupre  @djosborne ! The major thing is using default route for the out-going traffic, instead of specifying eth0 forcibly, in my understanding...

i need to add default route for my servers... :joy:
